### ISSUE TITLE
assign credentials

### ISSUE THREAD

**Issue by amandalegere** [harvesthq/harvest_api_samples#10]
Hello, I am referencing this code to make the API call from within the Visual Basic for Applications Editor I noticed you list the credentials (username and password) but where do you actually assign them to the httprequest? I am speaking of the vbs script example. I'm new to GetHub so please bare with me. Is this even a platform to ask questions on? LOL :) Thanks in advance!

**Comment by jasondew** [comment]
Hi @amandalegere ! I'm sorry for the super-late response, but, to answer your question, you'll need to edit the values here: 

https://github.com/harvesthq/harvest_api_samples/blob/master/harvest_api_sample.vbs#L19..L22
